// Generated by '@formkl/plugin-vite'
import type { Formkl, Theme } from "@formkl/shared";
import type { ComponentCustomProperties } from "vue";

declare module "vue" {
  interface ComponentCustomProperties {
    $formkl: {
      theme: Theme;
    };
  }
}

declare module "*.form" {
  const form: Formkl;
  export default form;
}

export {};
