// Generated by '@formkl/plugin-vite'
import type { Formkl } from "@formkl/shared";
import type { ComponentCustomProperties } from "vue";

declare module "*.form" {
  const form: Formkl;
  export default form;
}

export {};
