import { defineConfig } from "vite";
import path from "path";

export default defineConfig({
  build: {
    lib: {
      entry: path.resolve(__dirname, "src/index.ts"),
      name: "@formkl/shared",
      formats: ["es"], // adding 'umd' requires globals set to every external module
      fileName: (format) => `index.${format}.js`,
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
});
