<template>
  <div class="flex w-full justify-between">
    <div class="flex-1">
      <formkl-editor v-model="formklSyntax" />
    </div>
    <div class="flex-1 py-2 px-8">
      <Formkl ref="formklRef" :syntax="formklSyntax" @change="handleChange" />
    </div>
  </div>
</template>

<script lang="ts">
import { createForm } from "@formkl/adapter";
import { defineComponent, ref, h } from "vue";

const Formkl = createForm();

export default defineComponent({
  components: {
    Formkl,
  },
  setup() {
    const formklRef = ref();
    const formklSyntax = ref(`formkl
  "Your Formkl example"
  "This form is generated by the formkl adapter"
{
  multiple "Soem" includes {
    require text;
  }
  "jhk" includes {
    multiple text;
  }
}`);

    const submit = () => {
      formklRef.value?.submit$();
    };

    const handleChange = (value: any) => {
      console.log("handleChange", value);
    };

    return {
      formklRef,
      formklSyntax,
      submit,
      handleChange,
    };
  },
});
</script>
