<template>
  <div class="flex w-full justify-between">
    <div class="flex-1">
      <formkl-editor v-model="formklSyntax" />
    </div>
    <div class="flex-1 py-2 px-8">
      <Formkl ref="formklRef" :formkl="formklSyntax" />
    </div>
  </div>
</template>

<script lang="ts">
import { Formkl } from "@formkl/adapter";
import { defineComponent, ref } from "vue";

import "@formkl/editor";

export default defineComponent({
  components: {
    Formkl,
  },
  setup() {
    const formklRef = ref();
    const formklSyntax = ref(`formkl
  "Your Formkl example"
  "This form is generated by the formkl adapter"
{
  multiple "Soem" includes {
    require text;
  }
  "jhk" includes {
    multiple text;
  }
}`);

    const submit = () => {
      formklRef.value?.submit$();
    };

    return {
      formklRef,
      formklSyntax,
      submit,
    };
  },
});
</script>
