<template>
  <div class="flex w-full justify-between">
    <div class="flex-1">
      <FormklEditor v-model="formklSyntax" />
    </div>
    <div class="flex-1">
      <Formkl :formkl="formklSyntax" />
    </div>
  </div>
</template>

<script lang="ts">
import { Formkl } from "@formkl/vue";
import { FormklEditor } from "@formkl/editor";
import { defineComponent, ref } from "vue";

import "@formkl/vue/dist/style.css";
import "@formkl/editor/dist/style.css";

export default defineComponent({
  components: {
    Formkl,
    FormklEditor,
  },
  setup() {
    const formklSyntax = ref(`formkl
  "Your Formkl example"
  "This form is generated by the formkl adapter"
{
  "Something" includes {
    require "Email" text;
  }
}`);

    return {
      formklSyntax,
    };
  },
});
</script>
