packages:
  - "packages/**"
  - "sandbox"
catalog:
  "@codemirror/autocomplete": "^6.18.6"
  "@codemirror/commands": "^6.8.1"
  "@codemirror/lint": "^6.8.5"
  "@codemirror/state": "^6.5.2"
  "@codemirror/view": "^6.38.0"
  "@commitlint/cli": "^19.8.1"
  "@commitlint/config-conventional": "^19.8.1"
  "@nrwl/nx-cloud": "^19.1.0"
  "@nrwl/workspace": "^19.8.4"
  "@release-it/conventional-changelog": "^10.0.1"
  "@types/node": "^24.0.13"
  "@typescript-eslint/eslint-plugin": "^8.36.0"
  "@typescript-eslint/parser": "^8.36.0"
  "@vitejs/plugin-vue": "^6.0.0"
  "@vitejs/plugin-vue-jsx": "^5.0.1"
  "@vitest/ui": "^3.2.4"
  "@vue/test-utils": "^2.4.6"
  "@vue/tsconfig": "^0.7.0"
  "codemirror": "^6.0.2"
  "eslint": "^9.30.1"
  "es-toolkit": "^1.39.7"
  "element-plus": "^2.10.3"
  "husky": "^9.1.7"
  "jsdom": "^26.1.0"
  "nx": "^21.2.2"
  "release-it": "^19.0.3"
  "rimraf": "^6.0.1"
  "ts-node": "^10.9.2"
  "typescript": "^5.8.3"
  "unocss": "66.3.3"
  "unbuild": "^3.5.0"
  "unplugin-auto-import": "^0.17.1"
  "vite": "^7.0.4"
  "vite-plugin-dts": "^4.5.4"
  "vitest": "^3.2.4"
  "vitepress": "1.6.3"
  "vue": "^3.5.17"
  "vue-tsc": "^3.0.1"