module.exports = {
  Token: Object.freeze({
    STRING: "string",
    NUMBER: "number",
    LPAREN: "(",
    RPAREN: ")",
    LBRACE: "{",
    RBRACE: "}",
    LBRACK: "[",
    RBRACK: "]",
    COMMA: ",",
    COLON: ":",
    SEMICOLON: ";",
    GTEQ: ">=",
    LTEQ: "<=",
    EQ: "==",
    GT: ">",
    LT: "<",
    BREAKLINE: "\\n",
    TRUE: "true",
    FALSE: "false",
    NULL: "null",
    VALID: "valid",
    REGEX: "regex",
    REQUIRE: "require",
    OR: "or",
    AND: "and",
    FIELD: "field",
    FORMKL: "formkl",
    INCLUDES: "includes",
  }),
};
