module.exports = {
  Token: Object.freeze({
    FORMKL: "formkl",
    //
    STRING: "string",
    NUMBER: "number",
    TRUE: "true",
    FALSE: "false",
    NULL: "null",
    //
    LPAREN: "(",
    RPAREN: ")",
    LBRACE: "{",
    RBRACE: "}",
    LBRACK: "[",
    RBRACK: "]",
    COMMA: ",",
    COLON: ":",
    SEMICOLON: ";",
    NEQ: "!=",
    GTEQ: ">=",
    LTEQ: "<=",
    EQ: "==",
    GT: ">",
    LT: "<",
    BREAKLINE: "\\n",
    //
    REQUIRE: "require",
    AS: "as",
    OR: "or",
    AND: "and",
    HAS: "has",
    //
    FIELDVALIDATED: "fieldvalidated",
    FIELDDATETIME: "fielddatetime",
    FIELDSELECT: "fieldselect",
    FIELD: "field",
    INCLUDES: "includes",
    MULTIPLE: "multiple",
    BASE: "base",
    FLAT: "flat",
    //
    VALID: "valid",
    REGEX: "regex",
    URL: "url",
  }),
};
