import fs from 'node:fs'

import path from 'node:path'
import Formkl, { FormKitParser } from 'formkl'

export interface PluginDtsOptions {
  dir?: string
}

export interface PluginOptions {
  extenstion?: string
  formkit?: boolean
  dts?: boolean | PluginDtsOptions
}

export default (options?: PluginOptions) => {
  return {
    name: 'formkl-loader',
    buildStart() {
      const declaration = options?.formkit
        ? `// Generated by '@formkl/plugin-vite'
import type { Formkl } from "@formkl/shared";

declare module "*${options?.extenstion || '.form'}" {
  const form: Formkl;
  export default form;
}

export {};`
        : `// Generated by '@formkl/plugin-vite'
import type { FormKitSchemaDefinition } from '@formkit/core'

declare module "*${options?.extenstion || '.form'}" {
  const form: FormKitSchemaDefinition;
  export default form;
}
declare module "*${options?.extenstion || '.form'}?raw" {
  const form: string;
  export default form;
}

export {};`

      const dts = this.options?.dts || false
      if (dts !== false || (dts as any)?.dir) {
        fs.writeFile(
          path.resolve((dts as any)?.dir || './', 'form-shim.d.ts'),
          declaration,
          (err: any) => {
            if (err)
              throw err
          },
        )
      }
    },
    transform(code: string, id: string) {
      if (id.endsWith(options?.extenstion || '.form')) {
        let loadedFormModule = {}
        try {
          if (options?.formkit) {
            const formkitParser = new FormKitParser()
            // Parse Formkl syntax to FormKit schema
            loadedFormModule = formkitParser.parseToFormKit(code)
          }
          else {
            loadedFormModule = Formkl.parse(code)
          }
        }
        catch (error) {
          console.error(error)
        }

        return `export default ${JSON.stringify(loadedFormModule)}`
      }
      else if (id.endsWith(`${options?.extenstion || '.form'}?raw`)) {
        return code
      }
    },
  }
}
