import { createInput } from '@formkit/vue'
import { ElDatePicker } from 'element-plus'
import { defineComponent, h, markRaw } from 'vue'

// DateTimePicker wrapper component
const DateTimePickerWrapper = defineComponent({
  props: ['context'],
  setup(props) {
    return () => h(markRaw(ElDatePicker), {
      'modelValue': props.context._value,
      'onUpdate:modelValue': props.context.node.input,
      'onBlur': props.context.handlers.blur,
      'onFocus': props.context.handlers.focus,
      'readonly': props.context.readonly,
      'disabled': props.context.disabled,
      'editable': props.context.editable,
      'clearable': props.context.clearable,
      'size': props.context.size,
      'placeholder': props.context.placeholder,
      'startPlaceholder': props.context.startPlaceholder,
      'endPlaceholder': props.context.endPlaceholder,
      'type': props.context.dateTimeType || 'datetime',
      'format': props.context.format,
      'popper-class': props.context.popperClass,
      'range-separator': props.context.rangeSeparator,
      'default-value': props.context.defaultValue,
      'default-time': props.context.defaultTime,
      'value-format': props.context.valueFormat,
      'date-format': props.context.dateFormat,
      'time-format': props.context.timeFormat,
      'id': props.context.id,
      'name': props.context.name,
      'unlink-panels': props.context.unlinkPanels,
      'prefix-icon': props.context.prefixIcon,
      'clear-icon': props.context.clearIcon,
      'shortcuts': props.context.shortcuts,
      'disabled-date': props.context.disabledDate,
      'disabled-hours': props.context.disabledHours,
      'disabled-minutes': props.context.disabledMinutes,
      'disabled-seconds': props.context.disabledSeconds,
      'cell-class-name': props.context.cellClassName,
      'teleported': props.context.teleported,
      'empty-values': props.context.emptyValues,
      'value-on-clear': props.context.valueOnClear,
      'fallback-placements': props.context.fallbackPlacements,
      'placement': props.context.placement,
      'show-week-number': props.context.showWeekNumber,
      'show-now': props.context.showNow,
      'validate-event': props.context.validateEvent,
      'arrow-control': props.context.arrowControl,
    })
  },
})

// Export configured FormKit input
export const dateTimePickerInput = createInput(markRaw(DateTimePickerWrapper), {
  props: [
    'readonly',
    'disabled',
    'editable',
    'clearable',
    'size',
    'placeholder',
    'startPlaceholder',
    'endPlaceholder',
    'dateTimeType',
    'format',
    'popperClass',
    'rangeSeparator',
    'defaultValue',
    'defaultTime',
    'valueFormat',
    'dateFormat',
    'timeFormat',
    'id',
    'name',
    'unlinkPanels',
    'prefixIcon',
    'clearIcon',
    'shortcuts',
    'disabledDate',
    'disabledHours',
    'disabledMinutes',
    'disabledSeconds',
    'cellClassName',
    'teleported',
    'emptyValues',
    'valueOnClear',
    'fallbackPlacements',
    'placement',
    'showWeekNumber',
    'showNow',
    'validateEvent',
    'arrowControl',
  ],
})
