export enum DefaultComponent {
  CHECKBOX = "checkbox",
  DATE = "date",
  DATERANGE = "daterange",
  DATETIME = "datetime",
  DATETIMERANGE = "datetimerange",
  NUMBER = "number",
  PARAGRAPH = "paragraph",
  RADIO = "radio",
  SELECT = "select",
  SWITCH = "switch",
  TEXT = "text",
  TIME = "time",
  TIMERANGE = "timerange",
  FIELD_ADD_BTN = "fieldaddbtn",
  SECTION_ADD_BTN = "sectionaddbtn",
  FIELD_REMOVE_BTN = "fieldremovebtn",
  SECTION_REMOVE_BTN = "sectionremovebtn",
}
