import path from "path";
import { defineConfig } from "vite";

export default defineConfig({
  build: {
    lib: {
      name: "@formkl/editor",
      entry: path.resolve(__dirname, "./src/index.ts"),
      formats: ["es"], // adding 'umd' requires globals set to every external module
      fileName: (format: string) => `index.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: [
        "@codemirror/autocomplete",
        "@codemirror/commands",
        "@codemirror/lint",
        "@codemirror/state",
        "@codemirror/view",
        "codemirror",
        "formkl",
      ], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: "named",
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {},
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
});
