@{%
const lexer = require("./tokenizer.js");
const { tokenStart, tokenEnd, convertToken, convertTokenId } = require("./utils.js");
%}

# Pass your lexer with @lexer:
@lexer lexer

Section -> "{" FieldValidatedSet "}"
				| "{" EMPTY FieldValidatedSet "}"
				| "{" EMPTY FieldValidatedSet EMPTY "}"
				| "{" FieldValidatedSet EMPTY "}"

FieldValidatedSet -> null
								| FieldValidated
								| FieldValidated __ FieldValidatedSet
								| FieldValidated __ BR FieldValidatedSet
								| FieldValidated __ BR __ FieldValidatedSet

FieldValidated -> FIELD ";"
								| Label FIELD ";"
								| "require" __ FIELD ";"
								| "require" __ Label FIELD ";"


Label -> STRING __

EMPTY -> __
			| __ BR
			| BR __
			| __ BR __

__ -> %TkWhitespace:+

_ -> %TkWhitespace:*

FIELD -> %TkField {% convertTokenId %}

BR -> %TkLineBreak:+  {% convertTokenId %}

STRING -> %TkLitteralString {% convertTokenId %}

NUMBER -> %TkLitteralNumber {% convertTokenId %}
