name: Create Nx Report
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@latest
    with:
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx affected --target=build:all
        npx nx-cloud record -- npx nx affected --target=typecheck
        npx nx-cloud record -- npx nx affected --target=test
      parallel-commands-on-agents: |
        npx nx affected --target=build:all --parallel=3
        npx nx affected --target=typecheck --parallel=3
        npx nx affected --target=test --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@latest
    with:
      number-of-agents: 3
